# Generated by Django 4.1.2 on 2022-10-28 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelusers',
            name='id',
        ),
    ]
